usds/justice40-tool

server/docker-compose.yml

Fixes error flooding as follows:
```
db_1        | 2021-05-15 00:49:18.730 UTC [357] map_dev_user@map_dev LOG:  provided user name (map_dev_user) and authenticated user name (root) do not match
db_1        | 2021-05-15 00:49:18.730 UTC [357] map_dev_user@map_dev FATAL:  Peer authentication failed for user "map_dev_user"
db_1        | 2021-05-15 00:49:18.730 UTC [357] map_dev_user@map_dev DETAIL:  Connection matched pg_hba.conf line 94: "local   all             all                                     peer"
db_1        | 2021-05-15 00:49:23.857 UTC [365] map_dev_user@map_dev LOG:  provided user name (map_dev_user) and authenticated user name (root) do not match
db_1        | 2021-05-15 00:49:23.857 UTC [365] map_dev_user@map_dev FATAL:  Peer authentication failed for user "map_dev_user" …
```

Fix 'Peer authentication failed' error flooding in pg_isready

---

client/.vscode/launch.json
client/gatsby-config.js
client/gatsby-node.js
client/package-lock.json
client/package.json
client/src/components/J40footer.tsx
client/src/components/J40header.tsx
client/src/components/layout.module.scss
client/src/components/layout.module.scss.d.ts
client/src/components/layout.tsx
client/src/pages/index.tsx

* Add styles via sass and module imports
* Adds typed scss imports via gatsby-plugin-sass.
* Makes use of .d.scss file generated by gatsby-plugin-scss-typescript, but avoids importing that directly while they work out [an issue](https://github.com/Debens/gatsby-plugin-scss-typescript/issues/24) in gatsby v3.
* Creates basic layout component and two constituent components to illustrate the use of modules

Typed Sass Styling

---

.github/workflows/build_deploy.yml

Fixes issue #107 Geoplatform AWS throws errors on load - we had configured a prefix-path for use with github pages, but this didn't match the path within the s3 bucket. Upload content to a subfolder and ensure users access site from /justice40-tool/ . 
Additional benefit is that this fixes our CloudFront rendering, provided you supply this portion: https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/en/ now works to vend our latest site over https!

Fixes Geoplatform AWS errors on load

---

.github/workflows/build_deploy.yml
client/.vscode/launch.json
client/README.md
client/package-lock.json
client/package.json
client/src/components/J40Header.tsx
client/src/components/layout.tsx
client/src/contexts/FlagContext.test.tsx
client/src/contexts/FlagContext.tsx
client/src/pages/index.tsx
client/src/pages/timeline.tsx
client/src/styles/global.scss

Fixes #66: As a developer, I want to limit the audience that sees new features, so that we can control the message and positioning of our tool.
Implements simple feature flagging via URL parameters. Provide "?flags=x,y,z" to enable flags x, y, and z.
Also adds simple flagging for the "Timeline" feature: http://localhost:8000/?flags=timeline now shows the timeline.

Adding Simple URL-based feature flags

---

.github/workflows/build_deploy.yml
client/gatsby-config.js

Fixes #90 - adds a GHA SHA to PR branches and 'main' for merges to main
Adds a `DESTINATION_FOLDER` ENV var and consults it for setting prefix path and copying files.
Adding "draft" label for now as I need to prove that it actually works by running it first on GHA
As examples:
1. On PR
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/123431/en 
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/123431/en
2. On merge to main:
http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/main/en
https://d2zjid6n5ja2pt.cloudfront.net/justice40-tool/123431/en

Adding SHA (for PRs)/ Main (for main) to URL 

---

client/src/components/J40Aside.tsx
client/src/components/J40Header.tsx
client/src/pages/index.tsx
client/src/pages/timeline.tsx
client/src/styles/global.scss

"Fixes" #128 - cypress accessibility check was already there, this change just gets all the tests to pass.
Checkers (cypress and lighthouse) are at 100% for accessibility.
* Include a lang specification in the `<html>` tag. This is based on the `useIntl()` value.
* reorder `<h#>` header tags.
The `<Aside` to from `<h1>`, `<h2>` to be `<h2>`, `<h3>`. This is because trusswork's `<Footer>` uses and `<h4>` and the accessibility checkers complain it was skipping from `<h2>` -> `<h4>`
* Change `<aria-details>` to `<aria-label>` for milestone list.

Make the accessibility checkers happy

---

client/package-lock.json
client/package.json
client/src/components/map.tsx
client/tsconfig.json

For #100 - adding `ol-mapbox-style` to make styling a bit more standardized/straightforward. Note that this modifies our `tsconfig` to support JSDoc, which both `ol` and `ol-mapbox-styles` uses

Adding ol-mapbox-style for easier styling

---

.github/workflows/build_deploy.yml

Up to now, only deploying to PR-based hash directories has worked; this attempts to get things working for "main" as well, which will always point to the latest merged commit to main
Paradoxically, we won't know if this truly works until we merge this PR...

Fix Github Actions deploy for merges to main

---

client/gatsby-config.js

fixes #290 
It was determined that the files that prettier was suppose to _prettify_, was responsible for the error.
The gatsby-config file has a section where we define the files that prettier should [process](https://github.com/usds/justice40-tool/blob/7c9ce4110616eae2b28afb2391e7702dd64dacc0/client/gatsby-config.js#L38), via a `pattern` key. The pattern key is a string that defines various files types at any depth. This config file's prettier section was using the default settings to accommodate the most common file types.
The error was being thrown for the following files types: `json5`, `mdx`, `less`, `css`. When these superfluous files types were removed, the error was also removed.
**How was it determined if these patterns were ok to remove?**
Searching the `client` folder for …

fixes prettier error message during build

---

client/cypress/e2e/map.spec.js
client/src/components/J40Map.module.scss
client/src/components/J40Map.module.scss.d.ts
client/src/components/J40Map.tsx
client/src/data/constants.tsx

Fixes #280 - adds territory focus buttons for Alaska, Hawaii, Lower 48, and Puerto Rico to enable easy zoom to these locations. 
Not yet formally map controls, currently just buttons.

Add Zoom To Territory buttons for 48, AK, HI, and PR

---

client/cypress/e2e/map.spec.js
client/src/components/J40Map.tsx
client/src/data/constants.tsx
client/src/data/mapStyle.tsx

Fixes #201 - As an EVCM, I want the map to make sense at varying zoom levels so that I'm not confused . For now uses a usa_low tileset created as part of #209 for zoom levels 3-7. Will need further iteration.
For now uses a usa_low tileset created as part of #209 for zoom levels 3-7. Will need further iteration.

Adding low zoom level styling

---

client/src/components/J40Header.tsx
client/src/components/J40Map.tsx
client/src/contexts/FlagContext.test.tsx
client/src/contexts/FlagContext.tsx
client/src/data/constants.tsx
client/src/data/mapStyle.tsx

With this change, our `flags` parameter takes an argument , and our map style is set via a method. 
Combining these, we can do:
http://localhost:8000/en/cejst?flags=low_tiles=tract_low,high_tiles=0629_demo to set a bucket explicitly for low tiles and high 
(this change looks bigger than it is - it converts the flags to a dict, still supporting the old `flag=1` syntax but replacing it with a dict with values like `{1:true}`, and it converts the map style to use the `low_tiles` and `high_tiles` params

Parameterize zoom experiments

---

client/gatsby-ssr.js

Fix for issue #366
Created a gatsby-ssr.js to manually remove the css styles embedded in the pages.
SSR means "server side rendering". This fix is from a long github discussion about how broken including all css inline in the file is. 
The patch came from here: https://github.com/gatsbyjs/gatsby/issues/1526#issuecomment-433347822 
But honestly, I can't believe there is no flag to control this behavior and the issue was marked "Closed" by the Gatsby folks the way it works now. Especially since newer [CSP guidelines](https://content-security-policy.com/unsafe-inline/) say all css should be in a separate file.
The outputted file size for main `index.html`
```
Before:   462,099 bytes
After:      3,191 bytes
```
This is for _every single statically generated page_.
I tested locally but we …

Fix inlined css in every single page.

---

client/src/components/J40Footer.tsx
client/src/components/__snapshots__/J40Footer.spec.tsx.snap
client/src/intl/en.json
client/src/test/testHelpers.tsx

- Fixes #220
- Get snapshots working with Gatsby Intl plugin.
- Update the footer to match latest design
- Pull out strings to prep for localization
Reference for this fix and the corresponding `gatsby-plugin-intl` issue: https://github.com/wiziple/gatsby-plugin-intl/issues/90

Update footer to match latest design and fix intl+jest testing

---

client/src/components/territoryFocusControl.module.scss
client/src/styles/global.scss

Fixes #320, Zoom button styling does not match spec
Our buttons had a ghost shadow, because of the legacy of inherited styles. Need to reference [mapbox's css](https://github.com/mapbox/mapbox-gl-js/blob/main/src/css/mapbox-gl.css) to know how and what to override. Converted a few px's to ems along the way!

 Zoom button styling does not match spec

---

.github/workflows/build_deploy.yml

fixes #319 - merges to main still don't get posted to /main , and #362 It should be clearer how branches are deployed.
Specifically:
* Moves to using `pull_request` instead of `push` -- this is actually the correct event, as we want these flows to fire when opening and closing pull requests, not simply pushing. We can't push to master directly anyhow.
* Also imposes the restriction that if the PR is closed, and merged, then we should update the `main` URL; otherwise, we should use the hash. Both of these need to be true; we could theoretically close without merging or merge without closing. 
* Only comment with the deployment URL when the PR is opened - when it has been closed, all PRs will go to `/main`. 
* Bot now adds comment to the PR itself with the URL of the preferred deployment
* …

Merges to main don't get posted to main && it should be clearer how branches are deployed

---

data/data-pipeline/data_pipeline/application.py
data/data-pipeline/data_pipeline/etl/runner.py
data/data-pipeline/data_pipeline/etl/sources/census/etl.py

Fixes #473 - Census ETL should use standard ETL form
Reformats Census file to look and behave like other ETL classes; also separates out functionality into smaller, testable units

Census ETL should use standard ETL form

---

data/data-pipeline/data_pipeline/application.py
data/data-pipeline/data_pipeline/etl/sources/census/etl.py
data/data-pipeline/data_pipeline/utils.py

Moving from relative imports to absolute to enable `poetry run python …data-pipeline/application.py [command]`. Relative imports do not work if running the file directly. Still preferred to run `poetry run download_census`, which should always work, but we should support this alternative way of calling it also

Removes relative python imports

---

data/data-pipeline/data_pipeline/etl/constants.py
data/data-pipeline/data_pipeline/etl/runner.py
data/data-pipeline/data_pipeline/etl/sources/census/etl.py
data/data-pipeline/data_pipeline/etl/tests/test_etl.py

Adding back census to list of potential datasets, but separating out from standard list
Error this addresses:
File "/Users/lucas/Documents/usds/repos/justice40-tool/data/data-pipeline/data_pipeline/etl/runner.py", line 71, in etl_runner
f"data_pipeline.etl.sources.{dataset['module_dir']}.etl"
TypeError: 'NoneType' object is not subscriptable

'NoneType' object is not subscriptable because of missing census data

---

data/data-pipeline/.vscode/launch.json
data/data-pipeline/.vscode/settings.json
data/data-pipeline/.vscode/tasks.json
data/data-pipeline/README.md

Fixes #466 - Check in VSCode config for easier local debug
Makes it easier to run local debug through VSCode - these files aren't typically checked in on a project, but with this project things are a bit trickier given the use of click (which is a great library but makes testing a bit more difficult because of its use of `console_scripts`)

Check in VSCode config for easier local debug

---

data/data-pipeline/data_pipeline/etl/score/etl_score_post.py

Hello @BethMattern, 
I think you've already validated this in Slack, however just to be sure. Can you ensure that we've selected the correct columns from the CSV files to show percentile in the map's side panel when a CBG is selected?
Thank you!

sets column as percentiles

---

client/src/components/__snapshots__/scoreStepsList.test.tsx.snap
client/src/components/scoreStepsList.test.tsx
client/src/components/scoreStepsList.tsx
client/src/styles/global.scss

- Fixed the errors around putting other html elements inside `<p>` 
- Added Jest test to catch this mistake in the future. It does it by watching console.error().To add in fixing the bug the test's emulated `console.error()` are echoed to the jest console.error() so they are not lost. I tested this by putting a `<h1>` back into the `<p>` and it caught it.
We should figure out how to use this technique in more places?

Fix putting elements under <p>

---

client/compiled-lang/en.json
client/cypress/e2e/language.spec.js
client/cypress/e2e/map.spec.js
client/src/components/AboutCard/AboutCard.tsx
client/src/components/AboutCard/__snapshots__/AboutCard.test.tsx.snap
client/src/intl/en.json
client/src/pages/index.tsx

Closes #471 
There were two cypress tests that were failing
1. the about page
2. the map.spec
The about page required adding intl. Adding intl required re-running extract.
The map spec was failing on not have the zxy values match the test. Once those were fixed, there is an intermittent bug described here. #579  
This draft PR is to test if the nightly passes.

Nightly cypress failure mapspec

---

client/src/components/AreaDetail/areaDetail.module.scss
client/src/components/AreaDetail/areaDetail.module.scss.d.ts
client/src/components/AreaDetail/index.tsx
client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
client/src/components/AreaDetail/tests/areaDetail.test.tsx

Draft PR to get QA / test approval 
- aligns superscript position
- adds intl.plural rules fn to add ordinal superscripts
- updates units tests
- updates snapshot

Indicator percentiles shows two decimal places with ordinal superscript

---

data/data-pipeline/README.md
data/data-pipeline/data_pipeline/etl/score/etl_score.py
data/data-pipeline/data_pipeline/etl/sources/census_acs/etl.py
data/data-pipeline/data_pipeline/etl/sources/hud_housing/etl.py

This begins the refactor for #326. So far it keeps everything in the etl_score.py file but ssplits things into functions/methods so that they will be easier to pull out into classes later. 
I tested this as I went by having a separate git-tracked folder containing the contents of `data/score/csv/full` (one of the outputs of the score etl) originally creeated from the `main` branch. Then I would move newly generated contents from this branch to that folder to replace the original, and then do `git status` to see if anything had changed. Nothing showed a having changed.

Initial refactor for Score ETL

---

client/src/data/constants.tsx

In order for this to work, the PBF files for both the high and low zoom tiles will require the Score G key. This can be validated by running the [following](https://github.com/usds/justice40-tool/blob/main/client/VIEW_MAP_DATA.md#decoding-a-pbf-file) on the high and low zoom tiles.
TL;DR - an example of a low zoom tile (the z value in the url is 3):
```
curl https://d3jqyw10j8e7p9.cloudfront.net/data-pipeline/data/score/tiles/low/3/1/3.pbf -o d3_313.pbf
tippecanoe-decode d3_313.pbf 3 1 3 | jq
```
The output of tippecanoe-decode should have Score G key in the payload.
The same should happen with a high zoom tile.

Update to score G from score D

---

.github/workflows/main.yml

Based on @sverchdotgov 's https://github.com/sverchdotgov/github-actions-experiments/blob/master/.github/workflows/scheduled-email.yml
This is set to run every hour. We can modify as needed. It is also using our cloudfront URL and we'll need to change this to our new URL once we have it.

Add action for ping test and alert to Slack

---

client/src/components/LinkTypeWrapper/index.tsx
client/src/pages/__snapshots__/contact.test.tsx.snap
client/src/pages/__snapshots__/index.test.tsx.snap
client/src/pages/contact.tsx
client/src/pages/index.tsx

- allow contact page mailto link to open in new tab
- allow about page mailto link to open in new tab
- comment against opening external links in same tab
- 
Closes #718

Open external links in new tabs

---

client/src/data/copy/methodology.tsx
client/src/pages/__snapshots__/methodology.test.tsx.snap

I re-generated the download files today as part of #628 so needed to update the website to match.

Update site with latest download file date + size

---

data/data-pipeline/data_pipeline/etl/score/etl_score.py
data/data-pipeline/data_pipeline/etl/sources/housing_and_transportation/etl.py

Update data download URL to use tract as focus, use tract field name,
and move this dataset to the tracts df list in etl_score.
Closes #902

Move Housing and Transportation Index to tracts

---

data/data-pipeline/data_pipeline/etl/sources/census_acs/etl.py

Because of where this sneaky little `append` was in the code, if a call to the Census API failed (as it does for places like Guam and Virgin Islands), then it still appends the most recent value of `response`, which in this case was the data for Wyoming and Puerto Rico, which got appended multiple times.

Issue 932 fix too many tracts in ACS join

---

data/data-pipeline/data_pipeline/etl/constants.py
data/data-pipeline/data_pipeline/etl/score/etl_score.py
data/data-pipeline/data_pipeline/etl/sources/census_acs/etl.py
data/data-pipeline/data_pipeline/etl/sources/census_acs/etl_utils.py
data/data-pipeline/data_pipeline/etl/sources/child_opportunity_index/etl.py
data/data-pipeline/data_pipeline/score/field_names.py
data/data-pipeline/data_pipeline/score/score_l.py

Adds four fields: 
* Summer days above 90F 
* Percent low access to healthy food
* Percent impenetrable surface areas
* Low third grade reading proficiency 
Each of these four gets added into Definition L in various factors. 
Additionally, I add college attendance fields to the ETL for Census ACS. In another PR, I examine adding those to the definition L.
This PR also introduces the notion of "reverse percentiles", relevant to ticke #970. 
More information on COI: 
> COI compiles a number of useful data sets. In the future, we could pull these
> data sets in directly from their original creators.
> 
> Data dictionary available when you download zip from `self.COI_FILE_URL`.
> 
> Data source overview: https://data.diversitydatakids.org/dataset/coi20-child-opportunity-index-2-0-database.
> …

Issue 954: Add various data sources from Child Opportunity Index

---

.github/dependabot.yml

Showing obscure vulnerabilities that only exist in the dev setup creates
more noise and means that they just get ignored (because they are
probably low priority). Silencing them means when we get a vulnerable
dependency alert we know to pay attention to it.
Comes from https://github.com/dependabot/dependabot-core/issues/2521 and
https://github.com/hpcc-systems/Tombolo/commit/501bbef57817a9a46498095fdbd2e1e7a6ce62fa.

Silence dev only vulnerabilities

---

data/data-pipeline/data_pipeline/etl/sources/census_acs/etl_utils.py
data/data-pipeline/data_pipeline/etl/sources/census_acs_2010/etl.py

#1049. I noticed we were swallowing errors that happen on every request from the island territories. But this meant that new, unexpected errors were also getting swallowed, and the rest of the pipeline would run unaware that the source data was corrupted. 
This skips the island areas where we know Census ACS will never give us data, and raises all other errors.

Issue 1049: Stop swallowing Census API errors

---

client/cypress/integration/LegacyTests/mapZoomLatLong.spec.js
client/cypress/integration/LegacyTests/mapZoomTerritories.spec.js
client/src/components/AreaDetail/index.tsx
client/src/components/J40Map.tsx
client/src/components/territoryFocusControl.tsx
client/src/data/constants.tsx
client/src/data/copy/explore.tsx
docs/decisions/0002-mapping-visualization-library.md

It seems that when a tract is selected and/or the zoom level was above 8 (z>8), when clicking on a _territory shortcut_, e.g., `AS`, it would move the map over a tiny bit. This is because the click was registering as a click on the _map_ and NOT the territory shortcut `AS`.
We had two click handlers (one for _territory shortcuts_ and one for the _map_) firing each time the map was clicked. This meant either handler could handle the event. Normally `preventDefault()` or `stopPropagation()` are used to solve this, however for some reason it was not working in this case. 
Now we have a single click handler (aka [Event Delegation Pattern](https://dmitripavlutin.com/javascript-event-delegation/)) to handle both the _territory shortcut_ clicks and _map_ clicks. Now we decide based on the …

Fix territory shortcuts when census tract is selected

---

INSTALLATION-es.md
client/README.md
client/src/components/AreaDetail/areaDetail.module.scss
client/src/components/AreaDetail/areaDetail.module.scss.d.ts
client/src/components/AreaDetail/index.tsx
client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
client/src/components/BetaBanner/__snapshots__/BetaBanner.test.tsx.snap
client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
client/src/components/DatasetCard/index.tsx
client/src/components/DatasetCard/tests/__snapshots__/datasetCard.test.tsx.snap
client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
client/src/components/Indicator/Indicator.tsx
client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
client/src/data/copy/common.tsx
client/src/data/copy/explore.tsx
client/src/data/copy/methodology.tsx
client/src/pages/__snapshots__/contact.test.tsx.snap
client/src/pages/__snapshots__/index.test.tsx.snap
client/src/pages/__snapshots__/methodology.test.tsx.snap
client/src/styles/global.scss
docs/decisions/0002-mapping-visualization-library.md
docs/decisions/0004-client-side-framework.md

This PR:
1. adds header to each category
2. can create new paragraphs in methodology cards
3. can link to parts of `Responsible Party` text
4. can link to text in `Used In` text
5. adds Living Copy changes
This PR will add this to each category:
It also adds all the outstanding updates from Living Copy. In the Living Copy it was requested to make a separate paragraph for certain cards. This is now possible:
Maybe we want to break up this paragraph now that we can?
This PR also allows us now to modify the `Responsible party` links (add link to just a portion of the text rather than the entire text) as some links seem overwhelming (might just be me):
This PR also allows us to add links to the `Used In` field if it is desired. I thought this would be a nice way to connect it the Categories …

Add category header and updates from Living Copy

---

QUICKSTART.md

Just to set expectation that this will take a while, so new users don't think they did something wrong.

More obviously call out deploy time in quickstart

---

.github/workflows/markdown-link-check.yml
mlc_config.json

This makes sure that this action only runs if the pull request is on the main branch and is changing markdown files.
Fixes: https://github.com/usds/justice40-tool/issues/1114

Run markdown link checker only on markdown changes

---

data/data-pipeline/Dockerfile

Even though we want to use locked dependencies, pyproject.toml is still required.
Fixes: https://github.com/usds/justice40-tool/issues/1128

Add pyproject.toml to fix docker compose build

---

client/src/components/AreaDetail/index.tsx
client/src/data/constants.tsx

Update the boolean value that determines if the HS degree achievement indicator on the side panel is blue or not
closes #1148

Update boolean for HS degree indicator to LHE

---

client/src/components/AreaDetail/areaDetail.module.scss
client/src/components/AreaDetail/areaDetail.module.scss.d.ts
client/src/components/AreaDetail/index.tsx
client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
client/src/data/copy/contact.tsx
client/src/data/copy/explore.tsx
client/src/pages/__snapshots__/contact.test.tsx.snap
client/src/pages/contact.tsx

- Add send feedback button to side panel
- Make button open email in new tab with subject and body relevant to currently selected CBT
- update copy on contact page
closes #1158

Add Send feedback button census track feedback

---

data/data-pipeline/data_pipeline/etl/score/etl_score_geo.py

#1061 
Convert the CEJST data from geojson into ESRI shapefiles so that users who primarily use ArcGIS can easily load the CEJST data into their own tool.

Creating shapefiles for ArcGIS users

---

.github/ISSUE_TEMPLATE/pull_request_template.md
.github/workflows/compile_mermaid.yml
.github/workflows/deploy_be_staging.yml
.github/workflows/deploy_fe_staging.yml
.github/workflows/e2e.yml
client/README.md
docs/architecture/README.md

I was trying to track the experience of a new person trying to make a contribution. As I tried to do so the build failed due to links failing. I believe these links are failing because we may have updated master directly. I suggest we avoid that.
This PR will
- add a PR template to help OS contributors
- correct broken MD links
- make all YML files follow the same capital case naming scheme

Fix broken YML links and add PR template

---

client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
client/src/data/copy/methodology.tsx
client/src/pages/__snapshots__/methodology.test.tsx.snap

closes #1326 
- removes `proportions` and adds `percent` for poverty
- removes  `The` for linguistic iso and housing

Remove proportions and add percent

---

client/src/components/layout.tsx

Add meta tags for SEO

---

client/src/components/Language/Language.tsx
client/src/components/MapWrapper/index.tsx
client/src/components/territoryFocusControl.module.scss
client/src/pages/cejst.tsx

Remove color key from Explore the tool page

---

.github/workflows/deploy_fe_staging.yml
client/src/components/SidePanelInfo/__snapshots__/SidePanelInfo.test.tsx.snap
client/src/components/__snapshots__/mapInfoPanel.test.tsx.snap
client/src/data/copy/explore.tsx
client/src/intl/en.json

- Modify non-selected side panel based on CEQs latest updates
- closes #1359

Update sidepanel non-selected copy

---

client/src/components/AreaDetail/AreaDetail.tsx
client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
client/src/components/CategoryCard/__snapshots__/CategoryCard.test.tsx.snap
client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
client/src/data/constants.tsx
client/src/data/copy/explore.tsx
client/src/data/copy/methodology.tsx
client/src/intl/en.json
client/src/pages/__snapshots__/methodology.test.tsx.snap

Update the Higher Ed and High school to have all indicator thresholds in the same direction
- closes #1441 
Round 2:

Update copy for higher ed and high school

---

client/src/components/AreaDetail/AreaDetail.tsx
client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
client/src/components/AreaDetail/tests/areaDetail.test.tsx
client/src/components/J40Map.tsx
client/src/components/mapInfoPanel.tsx

The send feedback button creates an email with census tract info. It's sometimes hard to find the exact census tract. This PR will add the URL hash to the subject line allowing the support team to find the census tract with more ease.  This will place the URL hash in the subject line of the email
<details>
This PR will 
- detected bug with zoom/lat/lng values and created ticket 1550
- get realtime hash from mapRef
- pass hash to AreaDetail as prop
- update tests and snapshots
</details>
What should happen is that when the Send Feedback button is clicked in the side panel, it grabs the URL hash (at that exact moment in time) and places it in the subject line. If the map is changed (e.g. zooming in/out or panning) after the button is clicked, the new URL hash will not be captured in the …

Add hash to  send feedback email

---

client/src/components/J40Map.tsx

Integrate the tribal layer on to the map
The picture below shows how the tribal data was added
The colors above have no significance other than they are being used to illustrate how each layer is distinct.
This feature is behind a feature flag:
```
baseurl/?flags=tl
```
This feature changes the color of the airports.
Given the size of the tribal data, we will NOT incur an additional cost with this layer. The normal maploads allocation of 50k free maploads will still apply with no additional costs
closes tickets
- #1604 
- #1255
QA spec

Add tribal layer behind feature flag

---

client/src/components/Indicator/Indicator.test.tsx
client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
client/src/components/LinkTypeWrapper/LinkTypeWrapper.tsx
client/src/components/PublicEvent/PublicEvent.tsx
client/src/components/PublicVideoBox/PublicVideoBox.module.scss
client/src/components/PublicVideoBox/PublicVideoBox.tsx
client/src/components/PublicVideoBox/__snapshots__/PublicVideoBox.test.tsx.snap
client/src/components/RequestForInfo/__snapshots__/RequestForInfo.test.tsx.snap
client/src/data/copy/common.tsx
client/src/data/copy/publicEngage.tsx
client/src/intl/en.json
client/src/pages/public-engagement.tsx
client/src/pages/tests/__snapshots__/about.test.tsx.snap
client/src/pages/tests/__snapshots__/contact.test.tsx.snap
client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
client/src/pages/tests/__snapshots__/publicEng.test.tsx.snap
client/src/pages/tests/__snapshots__/techSupportDoc.test.tsx.snap

- closes #1602 
- closes #1595 
- closes #1593
- reverses the events in the PEC

Add TSD and RFI to alert, add link to download slides and reverse events in PEC

---

client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
client/src/components/SidePanelInfo/SidePanelInfo.module.scss
client/src/components/SidePanelInfo/SidePanelInfo.module.scss.d.ts
client/src/components/SidePanelInfo/SidePanelInfo.tsx
client/src/components/SidePanelInfo/__snapshots__/SidePanelInfo.test.tsx.snap
client/src/components/__snapshots__/mapInfoPanel.test.tsx.snap
client/src/data/copy/explore.tsx
client/src/data/copy/methodology.tsx
client/src/intl/en.json
client/src/intl/es.json
client/src/pages/tests/__snapshots__/methodology.test.tsx.snap

Add copy to sidepanel on unselected and correct typo on Traffic data

---

client/compiled-lang/en.json
client/src/components/DatasetCard/tests/__snapshots__/datasetCard.test.tsx.snap
client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
client/src/components/Indicator/Indicator.tsx
client/src/components/J40Footer/__snapshots__/J40Footer.spec.tsx.snap
client/src/components/SidePanelInfo/__snapshots__/SidePanelInfo.test.tsx.snap
client/src/components/__snapshots__/mapInfoPanel.test.tsx.snap
client/src/data/copy/common.tsx
client/src/data/copy/downloads.tsx
client/src/data/copy/explore.tsx
client/src/data/copy/faqs.tsx
client/src/data/copy/methodology.tsx
client/src/data/copy/publicEngage.tsx
client/src/data/copy/tsd.tsx
client/src/intl/en.json
client/src/intl/es_5.4.22-translated-final.json
client/src/pages/tests/__snapshots__/about.test.tsx.snap
client/src/pages/tests/__snapshots__/contact.test.tsx.snap
client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
client/src/pages/tests/__snapshots__/publicEng.test.tsx.snap
client/src/pages/tests/__snapshots__/techSupportDoc.test.tsx.snap

- closes #1629 
@katherinedm-usds - thanks for this exhaustive list of changes. It made checking and creating this QA spec very easy (it was just copy paste!) 
QA link for changes that are on the site are [here](http://usds-geoplatform-justice40-website.s3-website-us-east-1.amazonaws.com/justice40-tool/1648-f741d3/en/#3/33.47/-97.5).
QA link for changes that are just in the en.json file and not on the site is [here](https://github.com/usds/justice40-tool/blob/06d07da36dd311c2b409d0f7f5b2902b72eb818d/client/src/intl/en.json).
There are typos in the en.json that should be addressed
`    "defaultMessage": "Use the map to see communities that are identified as disadvantaged. The map uses publicly-available, nationally-consistent datasets. Learn more about the methodology and datasets that …

Fix typos found in en.json files and copy

---

client/src/data/constants.tsx

- Align zoom levels between the transition between low to high zoom with the census tract boundary
- closes #1645 
QA spec

Align zoom levels

---

data/data-pipeline/data_pipeline/etl/score/constants.py
data/data-pipeline/data_pipeline/etl/score/etl_score_post.py

Closes 1662.
This removes code that drops these two territories from the ETL and subsequent score data generation process.
Notably, tests are not currently passing on my machine (and they didn't pass before making the change). I need to figure that out before this can be fully done, assuming that this PR's build will fail when it runs the python tests.

Do not drop Guam and USVI from ETL

---

client/src/components/AreaDetail/AreaDetail.tsx
client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
client/src/components/Category/Category.tsx
client/src/components/DisadvantageDot/DisadvantageDot.tsx
client/src/components/ExceedBurden/ExceedBurden.tsx

- Add certain indicators to the side panel for Puerto Rico
- closes #1625 
QA spec

Add indicators to Puerto Rico (to release branch)

---

data/data-pipeline/data_pipeline/etl/score/etl_score.py
data/data-pipeline/data_pipeline/tests/score/fixtures.py
data/data-pipeline/data_pipeline/tests/score/test_calculation.py
data/data-pipeline/data_pipeline/tests/score/test_output.py

Add tests to make sure each source makes it to the score correctly

---

client/src/components/AreaDetail/AreaDetail.tsx
client/src/components/AreaDetail/areaDetail.module.scss
client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
client/src/components/Category/Category.module.scss
client/src/components/Category/Category.module.scss.d.ts
client/src/components/Category/Category.tsx
client/src/components/DisadvantageDot/DisadvantageDot.module.scss
client/src/components/Indicator/Indicator.module.scss
client/src/components/Indicator/Indicator.module.scss.d.ts
client/src/components/Indicator/Indicator.test.tsx
client/src/components/Indicator/Indicator.tsx
client/src/components/Indicator/__snapshots__/Indicator.test.tsx.snap
client/src/components/utils.scss
client/src/data/constants.tsx
client/src/data/copy/explore.tsx
client/src/data/copy/methodology.tsx
client/src/images/sidePanelIcons/accordion-minus.svg
client/src/images/sidePanelIcons/accordion-plus.svg
client/src/intl/en.json
client/src/styles/global.scss

- Update the indicator styles in the side panel for 1.0
Styling the categories entirely blue (with white +/-), didn't seem possible to me before browsers adopted the new CSS _psuedo-selector_ of `:has`. Check [here](https://caniuse.com/?search=has) to see the latest browser adoption.
Here's a pic showing what browser versions support the `:has` psuedo-selector:
In summary, the 
- **Chrome 105+** (anyone who updated their browser after 8/22/22) will show disadv. categories entirely blue with white +/-, otherwise fall back to beta style (blue dot)
- **Edge 105+** (anyone who updated their browser after 8/31/22) will show disadv. categories entirely blue with white +/-, otherwise fall back to beta style (blue dot)
- **Safari 15.4+** (anyone who updated their browser after 5/16/22) will show …

1.0 side panel indicator designs

---

data/data-pipeline/data_pipeline/etl/score/etl_utils.py
data/data-pipeline/data_pipeline/etl/sources/nlcd_nature_deprived/etl.py

It looks like I forgot to commit and push these changes that I made while wrapping up 1831. Pushing them now.
This code causes no functional change to the code. It does two things: 
1. Uses `difference` instead of `-` to improve code style for working with sets. 
2. Removes the line `EXPECTED_MISSING_STATES = ["02", "15"]`, which is now redundant because of the line I added (in a previous pull request) of `ALASKA_AND_HAWAII_EXPECTED_IN_DATA = False`.

1831 Follow up

---

data/data-pipeline/poetry.lock

Our virtualenv cache is broken, so I am trying to bump a single, non-build dependency to force it to rebuild.

Hotfix: Regenerate env cache

---

data/data-pipeline/data_pipeline/etl/sources/census_decennial/etl.py
data/data-pipeline/data_pipeline/etl/sources/tribal/etl.py

The old file had 24 missing geometries from the National LAR, for some reason. 
I uploaded two new zips to s3, refactored the ETL to point to them, and the problem is solved.

Issue 1944: Changing source of Tribal data file

---

data/data-pipeline/data_pipeline/etl/sources/michigan_ejscreen/README.md

This broken markdown link is causing the FE release branch to fail. Hoping to get this merged into main so that the FE release branch doesn't have to build the BE for each FE fix

Remove markdown link from markdown checker

---

data/data-pipeline/.pre-commit-config.yaml

Based on a great comment from @mattbowen-usds on a previous PR that I missed (https://github.com/usds/justice40-tool/pull/1962#discussion_r987226400).

No issue #: `black` update to remove specific version from pre-commit

---

.github/workflows/deploy_fe_staging.yml
client/package-lock.json
client/src/components/AreaDetail/AreaDetail.tsx
client/src/components/DonutCopy/DonutCopy.module.scss
client/src/components/DonutCopy/DonutCopy.module.scss.d.ts
client/src/components/DonutCopy/DonutCopy.test.tsx
client/src/components/DonutCopy/DonutCopy.tsx
client/src/components/DonutCopy/__snapshots__/DonutCopy.test.tsx.snap
client/src/components/DonutCopy/index.ts
client/src/components/Indicator/Indicator.module.scss
client/src/components/Indicator/Indicator.tsx
client/src/components/PrioritizationCopy/PrioritizationCopy.test.tsx
client/src/components/PrioritizationCopy/PrioritizationCopy.tsx
client/src/components/PrioritizationCopy/__snapshots__/PrioritizationCopy.test.tsx.snap
client/src/components/PrioritizationCopy2/PrioritizationCopy2.module.scss
client/src/components/PrioritizationCopy2/PrioritizationCopy2.module.scss.d.ts
client/src/components/PrioritizationCopy2/PrioritizationCopy2.test.tsx
client/src/components/PrioritizationCopy2/PrioritizationCopy2.tsx
client/src/components/PrioritizationCopy2/__snapshots__/PrioritizationCopy2.test.tsx.snap
client/src/components/PrioritizationCopy2/index.ts
client/src/components/TractPrioritization/TractPrioritization.module.scss
client/src/components/TractPrioritization/TractPrioritization.test.tsx
client/src/components/TractPrioritization/TractPrioritization.tsx
client/src/components/TractPrioritization/__snapshots__/TractPrioritization.test.tsx.snap
client/src/components/utils.scss
client/src/data/constants.tsx
client/src/data/copy/explore.tsx
client/src/intl/en.json

QA link [here](https://screeningtool-staging.geoplatform.gov/1990-b8e594/en/?flags=stage_hash=1822/baa34ec03844b4766f1dbb23dda0eca3c5b222e3#8.58/36.7274/-111.6747)

Updated side panel, with two paragraphs, "Completely surrounded" and "Adjusted low income" and more!

---

data/data-pipeline/data_pipeline/etl/sources/census_acs/etl_imputations.py

#1992. 
Weirdly, this doesn't seem to have affected any tracts? Because we already has this as a smoketest that was passing: 
```
tracts_with_null_population_df = final_score_df[
final_score_df[field_names.TOTAL_POP_FIELD].isnull()
]
assert (
tracts_with_null_population_df[
field_names.POVERTY_LESS_THAN_200_FPL_IMPUTED_FIELD
]
.isna()
.all()
)
```
So maybe the `null` population tracts got cast to `0` population somewhere in the scoring process?

Issue 1992: Do not impute income for null population tracts 

---

data/data-pipeline/data_pipeline/tile/generate.py

After initial analysis, we realized that tracts appear and disappear between zoom levels 5-7 because tippecanoe limits vector tiles to 500kb by default, and we were telling it to drop features to stay under that 500kb. For about 20% of tiles at zoom level 5, we can't stay easily under 500kb. To restore map functionality, we've removed these caps, and follow-on work will reduce the tile sizes as much as practical.

Disable file size limits on tiles

---

client/package-lock.json
client/package.json

This will update a transitive dependency to mitigate a security vulnerability flagged by dependabot.
For those that are able to do a PR review:
This will require a quick test on mobile. Warning: the mobile experience is far from great.  This test is mainly to increase confidence that regressions weren't introduced.
The direct dependency that was updated is used for mobile detection. Which is being used to render the map on mobile and also to handle the case when the open source community member isn't using Mapbox (paid). 
Regressions would be obvious like
1. map doesn't render
2. map is not clickable

fix: update ua-parser

---

data/data-pipeline/data_pipeline/application.py
data/data-pipeline/data_pipeline/utils.py

Two zip files were not getting cleared prior to running geo score; one of those was also not getting cleared before the full run. This resulted in them growing between runs until the application ground to a halt. This fix deletes those two zip files.

Add pre-cleaning to a couple of zip files during geo-score

---

.github/workflows/deploy_be_staging.yml
data/data-pipeline/data_pipeline/comparator.py

This PR adds the ability to perform a comparison between the published score and your local score. You can kick this off locally by calling `poetry run python3 data_pipeline/comparator.py compare-score`. It will also run as part of the staging backend deployment, and will add some summary comments to the PR. (This seemed like the most logical place to me, considering it's already generating the score and adding comments to the PR.)

Add ability to compare scores

---

client/src/components/Indicator/Indicator.tsx
client/src/intl/en.json

- closes #2187
QA:
This tract seems to have a good distribution of percentile values to test the ordinal suffix:
https://screeningtool-staging.geoplatform.gov/2188-2118bd/en/#10.87/35.4313/-91.7441

correct ordinal prefix for percentiles ending in 3

---

client/cypress/integration/Explore.feature
client/cypress/support/step_definitions/commonSteps.js
client/package-lock.json
client/package.json

This PR updates _minor_ FE dependencies to address issues pointed out by dependabot and by `npm audit`. (It does not tackle the larger ones, such as Gatsby.) It also fixes a few broken Cypress tests that popped up while updating the dependencies (the outstanding Cypress test failure is addressed in #2189).

Update minor frontend dependencies

---

client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
client/src/data/copy/methodology.tsx
client/src/pages/tests/__snapshots__/methodology.test.tsx.snap

Our Cypress tests found a dead link to EJScreen's technical documentation (404). This PR fixes that dead link (in multiple places) and updates the associated test snapshots.

Fix broken EJScreen Link

---

data/data-pipeline/poetry.lock

This PR bumps jupyter-core to a newer version to fix an issue identified by dependabot. 
It's a pretty minor update that only impacts the jupyter part of the process; I loaded up a few notebooks and everything opened and ran just like before. I also ran the pipeline just in case, and it ran fine.

Update jupyter-core dependency

---

data/data-pipeline/data_pipeline/application.py
data/data-pipeline/data_pipeline/etl/score/etl_score_geo.py

This PR consolidates the data that was in `/data/score/shapefile/columns.csv` into `/data/score/downloadable/xxx-codebook.csv`. We now have a single codebook with column names (the long ones), shapefile names (the short ones), and column definitions.
To avoid confusing people, we no longer include the `columns.csv` file in our zips (e.g. `xxx-shapefile-codebook.zip`); in fact, we don't even write it to disk anymore. We instead include the full codebook in our zip files. This should result in a more consistent and easier experience for consumers of our data.
On the technical side, the regular codebook is written during `generate-score-post`. During `geo-score` we add the shortened column names (the data that was previously in `columns.csv`) to the codebook, then package it all up in zip …

Consolidate columns.csv data into codebook

---

client/package-lock.json

This PR updates a handful of client packages to fix dependabot alerts. The long and short of it is that I ran `npm audit fix`, which addressed the two minor alerts (webpack and json5) that don't involve Gatsby. It also bumped minor versions of 5 other packages, which I'm sure dependabot would be complaining about soon.

Update Client packages
