- client/gatsby-node.js
- client/package-lock.json
- client/src/components/J40header.tsx
Temporarily removing the use of useStaticQuery as it seems to have introduced a bug in page rendering. Hard-coding for now; incidentally we will need to load this as a string anyway for localization purposes.
Also removing an attempt to use absolute module paths, to be readdressed later.
> Bug : staticrender results in page failing to load

- README.md
- docs/glossary.md
**Description**
We had a glossary in our open source kickoff and someone suggested putting it in our Github repo so that it lives on and is discoverable. This PR adds the initial version of the glossary including ways to update or submit new terms to the glossary.
> As an open source community member, I want to know what Justice40-specific terms and acronyms mean.

- .github/workflows/build_deploy.yml
- client/package-lock.json
- client/package.json
Addresses #11 sub-item "Security auditing"
Splitting dev and prod dependencies, adding npm audit step to catch security vulnerabilities
> Add security audit

- client/src/components/J40Footer.tsx
- client/src/components/__snapshots__/J40Footer.spec.tsx.snap
- client/src/pages/index.tsx
- client/src/styles/global.scss
- Get aside flush with top/bottom
- Media change iconlist to one column on mobile
- Misc other fixes
TODO: body font need to be addressed at the theme level?
> More layout fixes

- .github/workflows/build_deploy.yml
Addresses issue #97 - adding workflow to deploy to Geoplatform AWS.
> Deploy to Geoplatform AWS 

- client/src/components/J40Aside.tsx
- client/src/components/J40Footer.tsx
- client/src/components/__snapshots__/J40Footer.spec.tsx.snap
- client/src/pages/index.tsx
- client/src/pages/timeline.tsx
- client/src/styles/global.scss
- Add timeline page
- Factor out common aside into component.
TODO: Get nav menu working.
> Add timeline page

- .github/CODEOWNERS
- MAINTAINERS.md
- docs/README.md
Just the beginning :) the first PR.
> Added readme information under /docs about building and prerequisites

- COMMUNITY_GUIDELINES.md
- README.md
Update the repo with community guidelines shared and developed in our open source community chats.
> Add community guidelines

- client/src/components/layout.tsx
Small fix for #210 - work for trailing slash also
> Addresses #210, aside should not appear on map page

- client/src/pages/cejst.tsx
Previously part of demo branch, now breaking out as part of its own fix for clarity. There's definitely more to do for #199, but needed this for map display for now
> Addresses #199 - removing non-functioning layer switcher for now

- client/package-lock.json
- client/src/components/map.module.scss
- client/src/components/map.module.scss.d.ts
- client/src/components/map.tsx
- client/src/pages/cejst.tsx
Addresses #191 - "As a stakeholder interested in the cumulative impact score, I want to see more states in the map, so that I can further analyze the score results."
Will need further visual tweaks but this works with current data
> Issue 191 - Multi-state visualization

- .github/workflows/build_deploy.yml
One more attempt to fix merging to main, it appears it doesn't like curly brackets
> Attempt no. 2 to fix auto-generated `main` link

- client/src/components/HowYouCanHelp.tsx
- client/src/components/J40Header.tsx
- client/src/components/MapLegend.tsx
- client/src/pages/cejst.tsx
- client/src/pages/contact.tsx
- client/src/pages/index.tsx
- client/src/pages/methodology.tsx
- client/src/styles/global.scss
* add legend and styling for map page
* update header to latest style/content
* add contact page
* add methodology page
#199 and #200
> Site content and style update for sprint2/3

- client/cypress/e2e/map.spec.js
- client/src/components/J40Map.tsx
- client/src/components/popupContent.tsx
- client/src/data/constants.tsx
- client/src/data/mapStyle.tsx
Followup to https://github.com/usds/justice40-tool/pull/334 to add proper score property to popup. Changed property names but did not check this particular file.
> Followup styling fixes

- .github/workflows/e2e.yml
> cypress e2e nightly 

- client/cypress.json
- client/cypress/e2e/downloadPacket.spec.js
- client/src/components/downloadPacket.module.scss
- client/src/components/downloadPacket.module.scss.d.ts
- client/src/components/downloadPacket.test.tsx
- client/src/components/downloadPacket.tsx
- client/src/pages/cejst.module.scss
- client/src/pages/cejst.module.scss.d.ts
- client/src/pages/cejst.tsx
- client/src/styles/global.scss
closes #111 
Currently downloading this [csv](https://usds-geoplatform-justice40-website.s3.amazonaws.com/data/score/csv/usa.csv) as a placeholder for when the actual URL is determined.
> Allows the user to download CBG list

- .github/workflows/e2e.yml
- client/cypress/e2e/downloadPacket.spec.js
> updates filename and comments

- .github/CODEOWNERS
> Adding Vim to CODEOWNERS

- client/cypress/README.md
- client/cypress/e2e/accessibility.test.js
- client/cypress/e2e/language.spec.js
- client/cypress/e2e/latlngurl.spec.js
- client/cypress/e2e/map.spec.js
- client/cypress/support/commands.js
- client/src/components/territoryFocusControl.tsx
- client/src/intl/en.json
Fixes #373 - 
* Adding debug instructions for cypress tests
* Updating translation strings to get translation tests to pass
* Updating class names to get lat/lng tests to pass
* Localizing focus buttons on the way to adding proper area-labels for each button
* Removing buggy highlight test for now for map tests
* Setting accessibility bar to be "critical", to be updated later as part of accessibility audit #356
> Cypress tests are failing locally

- .github/ISSUE_TEMPLATE/dataset_request.yaml
Part of #262 - As a developer, I want to have a YAML file describing the metadata for our existing datasets 
This is an experimental attempt to add a github form for dataset requests , which will essentially auto-validate new dataset requests at the time of input by using newly-introduced [github issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository). 
We can then setup actions to parse this content and do things with it, using something like [this](https://github.com/peter-murray/issue-forms-body-parser)
> Adding template for dataset request

- docs/decisions/0008-nominatim.md
PR to add ADR for using Nominatim for search (associated with issue #402)
> Adding ADR PR for associated ADR issue #402

- data/data-pipeline/data_pipeline/etl/sources/census/etl.py
Fixes #467: If the census download task is run more than once, us.csv doubles in size and all data is removed from dataframe
Additionally updates census to use now-standard ETL structure
> Updating census ETL and checking for existing files

- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
A components snapshot wasn't updated. A few precommit hooks should be added. It has been captured here #495
> updates snapshot

- client/src/components/J40Footer.tsx
- client/src/components/__snapshots__/J40Footer.spec.tsx.snap
- client/src/pages/contact.tsx
Minor tweaks so we can close some issues.
See: #220 #352
> fix contact fix footer

- .github/workflows/build_deploy.yml
> Updating Front End Deploy Keys

- data/data-pipeline/README.md
We want to make the data usable/available at every step of our data
pipeline. This starts te addition to the README that spells out the data
provenance and where each version of the data as it goes through our
pipeline lives.
> Initial draft for data provenance addition to README

- .github/workflows/build_deploy.yml
- client/src/components/AreaDetail/areaDetail.module.scss
- client/src/components/AreaDetail/areaDetail.module.scss.d.ts
- client/src/components/AreaDetail/index.tsx
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/AreaDetail/tests/areaDetail.test.tsx
- client/src/components/DatasetContainer/index.tsx
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/J40Alert/index.tsx
- client/src/components/J40Alert/j40Alert.module.scss
- client/src/components/J40Alert/j40Alert.module.scss.d.ts
- client/src/components/J40Alert/tests/__snapshots__/j40Alert.test.tsx.snap
- client/src/components/J40Alert/tests/j40Alert.test.tsx
- client/src/components/J40Map.tsx
- client/src/components/MapWrapper/index.tsx
- client/src/components/mapInfoPanel.tsx
- client/src/data/constants.tsx
Draft PR to test CORS issue on deployed URL
>  update areaDetail with data from d3 CDN

- client/README.md
- client/VIEW_MAP_DATA.md
This was meant to capture the data flow between AWS and the app.
There are a number of things being explicitly talked about
1. CDN URLs (maybe not to bad to expose)
2. S3 URLs (might be worse to expose)
If anything on here is wrong or should not be made public. Please do let me know.
Thank you to all and especially Nat for bridging my understanding.
> adds VIEW_MAP_DATA readme

- .github/CODEOWNERS
- MAINTAINERS-es.md
- MAINTAINERS.md
This updates CODEOWNERS and MAINTAINERS.
> Update team member lists

- data/data-pipeline/data_pipeline/etl/score/etl_score_post.py
> added score D

- data/data-pipeline/data_pipeline/etl/score/etl_score_post.py
> Add to decimal rounding

- data/data-pipeline/README.md
- Added a link to the full score data set on S3
- Some Docker updates
> Updated README

- client/src/components/AreaDetail/index.tsx
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/DatasetContainer/index.tsx
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
> Update typos on copy

- .github/workflows/main.yml
Update name of workflow and only send slack notification on failure
> Update ping test workflow

- .github/workflows/deploy_main.yml
- .github/workflows/deploy_staging.yml
- client/gatsby-config.js
- client/src/components/zoomWarning.tsx
- When routing traffic to our new URL, the path prefix needs to be blank
- adding path prefix to be set by env var to yml files
> Add env variable to set path prefix

- client/src/components/AboutCard/AboutCard.tsx
- client/src/components/AboutCard/__snapshots__/AboutCard.test.tsx.snap
- client/src/components/LinkTypeWrapper/__snapshots__/linkTypeWrapper.test.tsx.snap
- client/src/components/LinkTypeWrapper/index.tsx
- client/src/components/LinkTypeWrapper/linkTypeWrapper.test.tsx
- client/src/pages/index.tsx
- AboutCard requires both internal and external links
- LinkTypeWrapper allows the component to specify link type
- add tests
> fix for internal links on about page

- .github/workflows/deploy_main.yml
- client/src/components/layout.tsx
- also add the geoplatform official site to yml file
> Add analytics script

- client/src/components/AreaDetail/areaDetail.module.scss
- client/src/components/AreaDetail/areaDetail.module.scss.d.ts
- client/src/components/AreaDetail/index.tsx
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/AreaDetail/tests/areaDetail.test.tsx
- client/src/components/MapLegend/mapLegend.module.scss
- make legend key a circle
- remove blue border in legend
- remove blue border in color key of side panel
closes #717
> Change map legend color key

- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/data/copy/methodology.tsx
- client/src/pages/__snapshots__/methodology.test.tsx.snap
- update snapshots
Note - aware of undefined in snapshots, ticket here
https://github.com/usds/justice40-tool/issues/513
> Update some additional dataset links

- client/gatsby-config.js
- client/package-lock.json
- client/package.json
- client/src/components/layout.tsx
- places original GA tag back into head
> Removes GA Gatsby plugin

- data/data-pipeline/data_pipeline/application.py
- data/data-pipeline/data_pipeline/etl/runner.py
- data/data-pipeline/data_pipeline/etl/score/constants.py
- data/data-pipeline/data_pipeline/etl/score/etl_score_post.py
- data/data-pipeline/data_pipeline/utils.py
Address #628 
This PR:
* Remove constants because we're dynamically creating these
* Update to "communities" for the descriptor word based on team convo
* Add timestamp in 2020-09-20-0930 format because I personally think this is the best ^.^ We can change it though
* Adds CLI for score post so we can easily just run that from the terminal
Still to do:
> Change downloadable file names

- .github/workflows/deploy_main.yml
- client/gatsby-config.js
- client/package-lock.json
- client/package.json
closes #679 
Triggering a purposeful runtime error and sentry caught it!
https://sentry.io/organizations/j40/issues/2687475285/?project=5989007
> Add sentry monitoring for all runtime errors

- .github/workflows/combine-tilefy.yml
- .github/workflows/generate-census.yml
- data/data-pipeline/data_pipeline/application.py
- data/data-pipeline/data_pipeline/etl/runner.py
- data/data-pipeline/data_pipeline/etl/score/etl_score.py
- data/data-pipeline/data_pipeline/etl/score/etl_score_geo.py
- data/data-pipeline/data_pipeline/etl/score/etl_score_post.py
- data/data-pipeline/data_pipeline/etl/sources/census/etl_utils.py
- data/data-pipeline/data_pipeline/utils.py
> Data sources from S3

- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
- client/src/data/copy/explore.tsx
- update snapshot
- closes #768
> Fix typos on Explore Tool page

- client/src/data/copy/explore.tsx
> Add version number

- client/cypress/integration/LegacyTests/mapZoomTerritories.spec.js
- client/src/components/AreaDetail/index.tsx
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/AreaDetail/tests/areaDetail.test.tsx
- client/src/components/J40Map.tsx
- client/src/data/constants.tsx
- add indicator values of selected CBG to console
- update snapshots
- update cypress tests (failure on zoom)
Closes #858 
Closes #855
> Fix AREA MEDIAN INCOME prop on map

- data/data-pipeline/data_pipeline/etl/score/etl_score.py
- data/data-pipeline/data_pipeline/etl/sources/census_acs/etl.py
- data/data-pipeline/data_pipeline/etl/sources/census_decennial/etl.py
- data/data-pipeline/data_pipeline/ipython/census_explore.ipynb
- data/data-pipeline/data_pipeline/ipython/scoring_comparison.ipynb
- data/data-pipeline/data_pipeline/score/field_names.py
- data/data-pipeline/data_pipeline/score/score_l.py
#864. This adds Median house value from Census ACS to the ETL as well as Definition L.
> Add median house value to Definition L

- data/data-pipeline/data_pipeline/etl/score/etl_score.py
- data/data-pipeline/data_pipeline/ipython/scoring_comparison.ipynb
- data/data-pipeline/data_pipeline/score/field_names.py
Fixes a small bug from a field that no longer exists.
> Fix FEMA issues

- data/data-pipeline/data_pipeline/etl/sources/census_decennial/etl.py
Just standardizing the directory name.
> Quick fix on island territories directory name

- data/data-pipeline/data_pipeline/etl/sources/census_decennial/etl.py
I created this to run some analytics. When the `mega-tracts-trunk` is ready we can point this PR there.
> Switching island territories Census data to tracts

- data/data-pipeline/data_pipeline/etl/score/etl_score.py
- data/data-pipeline/data_pipeline/etl/sources/census_acs/etl.py
> Use tract instead of block group when calling census API

- data/data-pipeline/data_pipeline/etl/sources/census/etl.py
> Esfoobar usds/835 census tracts geojson

- data/data-pipeline/data_pipeline/etl/score/etl_score.py
- data/data-pipeline/data_pipeline/etl/sources/ejscreen/etl.py
> EJScreen Tracts

- data/data-pipeline/data_pipeline/etl/base.py
- data/data-pipeline/data_pipeline/etl/constants.py
- data/data-pipeline/data_pipeline/etl/score/etl_score.py
- data/data-pipeline/data_pipeline/etl/sources/census_decennial/etl.py
- data/data-pipeline/data_pipeline/etl/sources/ejscreen/etl.py
- data/data-pipeline/data_pipeline/etl/sources/housing_and_transportation/etl.py
- data/data-pipeline/data_pipeline/score/score_c.py
It turns out the CNT data had duplicate tract values, so I removed that source since it's no longer in score L. 
Also created some cleaner sanity checking methods around the dataframes.
> Issue 919: Fix too many tracts issue

- data/data-pipeline/data_pipeline/etl/score/etl_score_geo.py
> Tract work score geo

- data/data-pipeline/data_pipeline/etl/sources/census_acs/etl.py
To allow future users to run their own analyses.
> Adding some demographics information to ETL source data

- client/src/components/AreaDetail/index.tsx
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
> Shows N/A when data is not present on selected track

- data/data-pipeline/data_pipeline/ipython/compare_two_score_files_for_differences.ipynb
I created this because I wanted to check the results of the score file before and after some massive refactors we've been doing. So far the results look good!
> Creating notebook to compare two score files for differences

- data/data-pipeline/data_pipeline/etl/score/etl_score.py
- data/data-pipeline/data_pipeline/score/field_names.py
Adds apples-to-apples percentiles, finishing issue #967 .
> Issue 967: Calculate urban/rural percentiles

- client/cypress/integration/AboutLinks.feature
- client/cypress/integration/LegacyTests/mapZoomLatLong.spec.js
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
- client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
- client/src/components/MapLegend/tests/__snapshots__/mapLegend.test.tsx.snap
- client/src/components/MapWrapper/index.tsx
- client/src/components/SurveyButton/SurveyButton.module.scss
- client/src/components/__snapshots__/mapInfoPanel.test.tsx.snap
- client/src/components/mapIntroduction.test.tsx
- client/src/data/copy/404.tsx
- client/src/data/copy/about.tsx
- client/src/data/copy/common.tsx
- client/src/data/copy/explore.tsx
- client/src/data/copy/methodology.tsx
- client/src/pages/404.tsx
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/__snapshots__/index.test.tsx.snap
- client/src/pages/__snapshots__/methodology.test.tsx.snap
- client/src/pages/index.tsx
- client/src/styles/global.scss
closes #908 
closes #958
closes #760
> Modify copy on About and Explore Tool pages

- client/src/components/J40Map.tsx
- client/src/components/MapWrapper/index.tsx
- client/src/components/territoryFocusControl.tsx
- client/src/data/copy/explore.tsx
closes #1020 
- comment out GU and VI code
- remove search from feature flag
- keep comment on search production bug when wrapping div
- add note on territories
- add territories copy to constants
> Remove GU, VI from UI and remove Search from feature flag

- client/src/components/GovernmentBanner/GovernmentBanner.tsx
- client/src/components/GovernmentBanner/__snapshots__/GovernmentBanner.test.tsx.snap
- client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
- client/src/components/Language/Language.tsx
- client/src/components/Language/__snapshots__/Language.test.tsx.snap
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/__snapshots__/index.test.tsx.snap
- client/src/pages/__snapshots__/methodology.test.tsx.snap
closes #1017 
To enable -  ?flags=sp
> Place spanish content on feature ?flags=sp

- client/cypress/integration/AboutLinks.feature
- client/src/components/AreaDetail/areaDetail.module.scss
- client/src/components/AreaDetail/areaDetail.module.scss.d.ts
- client/src/components/AreaDetail/index.tsx
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/BetaBanner/__snapshots__/BetaBanner.test.tsx.snap
- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/components/Category/Category.module.scss
- client/src/components/Category/Category.module.scss.d.ts
- client/src/components/Category/Category.tsx
- client/src/components/DatasetCard/tests/__snapshots__/datasetCard.test.tsx.snap
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
- client/src/components/J40Footer.tsx
- client/src/components/J40Header/J40Header.module.scss
- client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
- client/src/components/MapLegend/tests/__snapshots__/mapLegend.test.tsx.snap
- client/src/components/SurveyButton/__snapshots__/SurveyButton.test.tsx.snap
- client/src/components/__snapshots__/J40Footer.spec.tsx.snap
- client/src/components/__snapshots__/mapInfoPanel.test.tsx.snap
- client/src/data/blankCEJST/index.html
- client/src/data/constants.tsx
- client/src/data/copy/about.tsx
- client/src/data/copy/common.tsx
- client/src/data/copy/contact.tsx
- client/src/data/copy/explore.tsx
- client/src/data/copy/methodology.tsx
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/__snapshots__/index.test.tsx.snap
- client/src/pages/__snapshots__/methodology.test.tsx.snap
Purpose of this PR:
1. latest living copy changes
2. add HS edu back to side panel
3. add number of thresholds exceed to side panel
> Make latest copy changes from Living Copy

- data/data-pipeline/data_pipeline/ipython/experiment_4_weighting/health_scores.py
> Fix errors and improve code quality and readability in Health Scores

- client/src/data/getOSBaseMap.tsx
> Fix console errors when loading the open source base map

- .github/workflows/score-checks.yml
> Score run on every commit to data PR

- client/src/components/territoryFocusControl.tsx
> Add tooltip to territory buttons

- data/data-pipeline/data_pipeline/etl/score/constants.py
- data/data-pipeline/data_pipeline/etl/score/etl_score_post.py
#1003
Not the most elegant solution, but I get the sense this will be relatively temporary? 
Only USVI and Guam FIPS codes (66, 78) have been removed.
> Remove USVI and Guam territories from data and include/show on map American Samoa and Mariana Islands

- .github/workflows/deploy_fe_main.yml
- client/cypress/integration/DatasetLinks.feature
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/components/DatasetCard/tests/__snapshots__/datasetCard.test.tsx.snap
- client/src/components/DatasetContainer/index.tsx
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
- client/src/components/LowIncome/__snapshots__/LowIncome.test.tsx.snap
- client/src/components/MapLegend/tests/__snapshots__/mapLegend.test.tsx.snap
- client/src/components/MapWrapper/index.tsx
- client/src/components/__snapshots__/mapInfoPanel.test.tsx.snap
- client/src/data/copy/about.tsx
- client/src/data/copy/contact.tsx
- client/src/data/copy/explore.tsx
- client/src/data/copy/methodology.tsx
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/__snapshots__/index.test.tsx.snap
- client/src/pages/__snapshots__/methodology.test.tsx.snap
Closes #1197 
Closes #1208 
Closes #1174
Closes #1265
Closes #1204
Closes #1206
Closes #1202
> Update side panel copy to Living copy

- client/src/components/AreaDetail/AreaDetail.tsx
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/DisadvantageDot/DisadvantageDot.module.scss
- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
- client/src/components/Indicator/Indicator.tsx
- client/src/components/MapLegend/index.tsx
- client/src/components/MapLegend/mapLegend.module.scss
- client/src/components/MapLegend/mapLegend.module.scss.d.ts
- client/src/components/MapLegend/tests/__snapshots__/mapLegend.test.tsx.snap
- client/src/data/constants.tsx
- client/src/data/copy/explore.tsx
- modify map legend, add color key and circle stroke
- add Higher ed to sidepanel
- remove coercion of 0 to N/A on sidepanel
- update snapshots
- closes #1301 
- closes #1302 
- closes #1294
- closes #1303
- closes #1259
> Update copy and sidepanel

- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
- client/src/data/copy/explore.tsx
> Add RFI link

- client/src/components/MethodologyFormula/__snapshots__/MethodologyFormula.test.tsx.snap
- client/src/data/copy/methodology.tsx
- client/src/pages/__snapshots__/methodology.test.tsx.snap
> Update formula copy

- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/components/CategoryCard/__snapshots__/CategoryCard.test.tsx.snap
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/MethodologyFormula/__snapshots__/MethodologyFormula.test.tsx.snap
- client/src/data/copy/methodology.tsx
- client/src/pages/__snapshots__/methodology.test.tsx.snap
- add the before percentile
- change to exceeds
Closes #1315
> Add THE to percentiles

- client/src/data/copy/contact.tsx
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/contact.tsx
Fix typo on contact page tracks to tract
> Fix typo on contact page, track to tracts

- data/data-pipeline/README.md
- data/data-pipeline/data_pipeline/application.py
Fixes #1362.
This PR reduces the brand-new Docker setup for users from more than an hour to around 30 minutes and also avoids issues with external data sources rate limiting or networking issues, relying fully on our S3-based score.
The PR also adds the ArcGIS shape files URL.
> Reducing Docker start up and adding ArcGIS URL

- .github/workflows/deploy_be_staging.yml
- data/data-pipeline/README.md
- data/data-pipeline/data_pipeline/etl/score/constants.py
- data/data-pipeline/data_pipeline/etl/score/etl_score_geo.py
> ArcGIS zipping

- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
- client/src/components/MapLegend/tests/__snapshots__/mapLegend.test.tsx.snap
- client/src/components/MethodologyFormula/__snapshots__/MethodologyFormula.test.tsx.snap
- client/src/components/__snapshots__/mapInfoPanel.test.tsx.snap
- client/src/data/copy/about.tsx
- client/src/data/copy/contact.tsx
- client/src/data/copy/explore.tsx
- client/src/data/copy/methodology.tsx
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/__snapshots__/index.test.tsx.snap
- client/src/pages/__snapshots__/methodology.test.tsx.snap
- closes #1358 
- closes #1396
> Add consistency copy changes from CEQ

- .github/workflows/deploy_fe_staging.yml
- client/.husky/pre-commit
- client/package-lock.json
- client/package.json
- client/src/data/copy/contact.tsx
- client/src/data/copy/explore.tsx
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- closes #1373 
- will add Husky lib
- will add pre-commit script that will run `intl:extract`, detect any `warnings` on extraction and abort commit
- update deploy staging yml to show message that en.json was modified
> Add intl pre-commit hook and update GHA

- .github/workflows/deploy_fe_staging.yml
- client/src/intl/en.json
- Update the FE stage deployment script
- Commit latest es.json changes (pre-commit hook!)
> Add release branch to frontend deploy staging

- client/cypress/integration/About.feature
- client/src/components/AreaDetail/AreaDetail.tsx
- client/src/components/J40Header/J40Header.module.scss
- client/src/components/J40Header/J40Header.module.scss.d.ts
- client/src/components/J40Header/J40Header.tsx
- client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
- client/src/components/PublicEngageButton/PublicEngageButton.tsx
- client/src/components/PublicEngageButton/__snapshots__/PublicEngageButton.test.tsx.snap
- client/src/data/copy/common.tsx
- client/src/data/copy/contact.tsx
- client/src/data/copy/explore.tsx
- client/src/intl/en.json
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/__snapshots__/index.test.tsx.snap
- client/src/pages/__snapshots__/methodology.test.tsx.snap
- client/src/pages/contact.tsx
- client/src/pages/index.tsx
Bring attention to the new census track side panel
> Add wording to UI that calls out improvements to display of census tract information

- client/src/components/AreaDetail/AreaDetail.tsx
- client/src/components/AreaDetail/areaDetail.module.scss
- client/src/components/AreaDetail/areaDetail.module.scss.d.ts
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/AreaDetail/tests/areaDetail.test.tsx
- client/src/components/ExceedBurden/__snapshots__/ExceedBurden.test.tsx.snap
- client/src/data/constants.tsx
- client/src/data/copy/explore.tsx
- client/src/intl/en.json
Make the count of thresholds exceeded on the side panel more clear
- closes #1403
> Make the count of thresholds exceeded on the side panel more clear

- client/src/components/RequestForInfo/RequestForInfo.module.scss
- client/src/components/RequestForInfo/RequestForInfo.module.scss.d.ts
- client/src/components/RequestForInfo/RequestForInfo.test.tsx
- client/src/components/RequestForInfo/RequestForInfo.tsx
- client/src/components/RequestForInfo/__snapshots__/RequestForInfo.test.tsx.snap
- client/src/components/RequestForInfo/index.tsx
- client/src/data/copy/contact.tsx
- client/src/intl/en.json
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/contact.tsx
- client/src/styles/global.scss
Add RFI to contact page
- closes #1442 
QA round 2:
> Add RFI to contact page

- client/src/components/PublicEvent/PublicEvent.tsx
- client/src/data/copy/publicEngage.tsx
- client/src/intl/en.json
Update WHEJAC meetings body
- closes #1520
> Update copy of WHEJAC meetings

- client/cypress/integration/Contact.feature
- client/src/components/DownloadPacket/index.tsx
- client/src/components/RequestForInfo/RequestForInfo.module.scss
- client/src/components/RequestForInfo/RequestForInfo.module.scss.d.ts
- client/src/components/RequestForInfo/RequestForInfo.test.tsx
- client/src/components/RequestForInfo/RequestForInfo.tsx
- client/src/components/RequestForInfo/__snapshots__/RequestForInfo.test.tsx.snap
- client/src/components/RequestForInfo/index.tsx
- client/src/data/copy/contact.tsx
- client/src/intl/en.json
- client/src/pages/__snapshots__/contact.test.tsx.snap
- client/src/pages/__snapshots__/methodology.test.tsx.snap
- client/src/pages/contact.tsx
- client/src/styles/global.scss
- Add RFI box / link to contact page
- fix local cypress errors
> RFI link to contact page

- data/data-pipeline/data_pipeline/etl/score/etl_score_geo.py
- data/data-pipeline/poetry.lock
This PR adds the csv column descriptions to the shapefile, while keeping original column names as well (in case we refactor and change the names). 
This is a little bit clumsy in that it takes place in etl score geo, but there isn't really a great place to put it right now.
> Adding updated codebook to shapefile zip

- client/VIEW_MAP_DATA.md
- client/compiled-lang/en.json
- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/components/CategoryCard/__snapshots__/CategoryCard.test.tsx.snap
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
- client/src/components/RequestForInfo/__snapshots__/RequestForInfo.test.tsx.snap
- client/src/components/mapInfoPanel.test.tsx
- client/src/data/copy/common.tsx
- client/src/data/copy/contact.tsx
- client/src/data/copy/explore.tsx
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- client/src/intl/esNoBrackets.json
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
- client/src/pages/tests/__snapshots__/contact.test.tsx.snap
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- client/src/pages/tests/__snapshots__/publicEng.test.tsx.snap
- client/src/pages/tests/__snapshots__/techSupportDoc.test.tsx.snap
Fixes #1572 and #1562
Some of snapshots were updated that I didn't change when I ran `test:update`. I suspect this was just an oversight from previous changes? I ran `test` and everything passed.
Note: The `en.json` file was updated and will likely need to be run through translation again.
> Minor edits to copy - Fixes #1572

- client/compiled-lang/en.json
- client/src/components/J40Header/J40Header.tsx
- client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
- client/src/components/RequestForInfo/RequestForInfo.tsx
- client/src/components/RequestForInfo/__snapshots__/RequestForInfo.test.tsx.snap
- client/src/data/copy/common.tsx
- client/src/intl/en.json
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
- client/src/pages/tests/__snapshots__/contact.test.tsx.snap
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- client/src/pages/tests/__snapshots__/publicEng.test.tsx.snap
- client/src/pages/tests/__snapshots__/techSupportDoc.test.tsx.snap
> Change primary alert message, expiration date, update intl and tests

- client/compiled-lang/en.json
- client/src/components/DownloadPacket/DownloadPacket.tsx
- client/src/components/DownloadPacket/__snapshots__/downloadPacket.test.tsx.snap
- client/src/components/DownloadPacket/downloadPacket.module.scss
- client/src/components/DownloadPacket/downloadPacket.module.scss.d.ts
- client/src/components/J40Header/J40Header.tsx
- client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
- client/src/data/copy/common.tsx
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
- client/src/pages/tests/__snapshots__/contact.test.tsx.snap
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- client/src/pages/tests/__snapshots__/publicEng.test.tsx.snap
- client/src/pages/tests/__snapshots__/techSupportDoc.test.tsx.snap
- Fixes #1567
- Cleaned up styles related to buttons.
- Refactored buttons a little to make easier to maintain.
- Updated test snapshots/translation files
-
> Update Download sidebar, add new alert

- client/src/data/copy/explore.tsx
- client/src/intl/en.json
> Update copy under map

- client/compiled-lang/en.json
- client/src/components/DownloadPacket/__snapshots__/downloadPacket.test.tsx.snap
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
I missed this the first time around.
Also, updated intl and tests snapshots.
> Put codebook into <callout></callout> section for Download description

- client/src/components/RequestForInfo/__snapshots__/RequestForInfo.test.tsx.snap
- client/src/components/SidePanelInfo/__snapshots__/SidePanelInfo.test.tsx.snap
- client/src/components/__snapshots__/mapInfoPanel.test.tsx.snap
- client/src/data/copy/contact.tsx
- client/src/data/copy/explore.tsx
- client/src/intl/en.json
- client/src/intl/es.json
- client/src/pages/tests/__snapshots__/contact.test.tsx.snap
- closes #1647 
- add missing period to RFI
> Changes criteria to criterion

- client/src/components/Indicator/Indicator.test.tsx
- client/src/components/Indicator/Indicator.tsx
- client/src/components/Indicator/__snapshots__/Indicator.test.tsx.snap
Replace indicator rounding with flooring
QA Spec
> Change round to floor for indicator values

- client/gatsby-config.js
- client/package-lock.json
- client/package.json
- upgrade @sentry
- place sentry dsn in github secrets
> hotfix for terser dependabot failure

- .github/workflows/deploy_fe_staging.yml
- client/src/data/blankCEJST/index.html
> Update Cypress GHA to v4

- .github/workflows/tribal-deploy.yml
- data/data-pipeline/.vscode/launch.json
- data/data-pipeline/data_pipeline/application.py
- data/data-pipeline/data_pipeline/etl/constants.py
- data/data-pipeline/data_pipeline/etl/runner.py
- data/data-pipeline/data_pipeline/etl/sources/census/etl.py
- data/data-pipeline/data_pipeline/etl/sources/tribal/etl.py
- data/data-pipeline/data_pipeline/etl/sources/tribal/etl_utils.py
- data/data-pipeline/data_pipeline/tile/generate.py
Fixes #1725. #1726, #1727 and #1728.
> Starting Tribal Boundaries Work

- client/src/components/AreaDetail/tests/__snapshots__/areaDetail.test.tsx.snap
- client/src/data/copy/explore.tsx
- client/src/intl/en.json
- client/src/intl/es.json
> Correct copy typo on building loss rate

- data/data-pipeline/data_pipeline/etl/base.py
- data/data-pipeline/data_pipeline/tests/sources/doe_energy_burden/test_etl.py
- data/data-pipeline/data_pipeline/tests/sources/eamlis/test_etl.py
- data/data-pipeline/data_pipeline/tests/sources/example/test_etl.py
- data/data-pipeline/data_pipeline/tests/sources/us_army_fuds/test_etl.py
Lucas has helpful feedback on the source tests, and these implement them
> Cleanup source tests

- .github/workflows/data-checks.yml
- data/data-pipeline/data_pipeline/ipython/check_tribal_count.ipynb
> Add tribal count notebook (#1917)

- data/data-pipeline/poetry.lock
> Update deps safety says are vulnerable (#1937)

- client/src/components/J40Footer/__snapshots__/J40Footer.spec.tsx.snap
- client/src/components/J40Map.tsx
- client/src/components/PrioritizationCopy/__snapshots__/PrioritizationCopy.test.tsx.snap
- client/src/components/SurveyButton/__snapshots__/SurveyButton.test.tsx.snap
- client/src/data/copy/contact.tsx
- client/src/data/copy/explore.tsx
- client/src/intl/en.json
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
- client/src/pages/tests/__snapshots__/contact.test.tsx.snap
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- client/src/pages/tests/__snapshots__/publicEng.test.tsx.snap
- client/src/pages/tests/__snapshots__/techSupportDoc.test.tsx.snap
closes #1945 
closes #1950 
closes #1951 
closes #1967 
closes #1959
> Update copy based on bug party

- client/.env.development
- client/src/components/Categories/Categories.module.scss
- client/src/components/Categories/Categories.module.scss.d.ts
- client/src/components/Categories/Categories.tsx
- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/components/CategoryCard/CategoryCard.tsx
- client/src/components/CategoryCard/__snapshots__/CategoryCard.test.tsx.snap
- client/src/components/DatasetCard/DatasetCard.tsx
- client/src/components/DatasetCard/tests/__snapshots__/datasetCard.test.tsx.snap
- client/src/components/DatasetContainer/index.tsx
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/DatasetsButton/DatasetsButton.module.scss
- client/src/components/DatasetsButton/DatasetsButton.module.scss.d.ts
- client/src/components/DatasetsButton/DatasetsButton.test.tsx
- client/src/components/DatasetsButton/DatasetsButton.tsx
- client/src/components/DatasetsButton/__snapshots__/DatasetsButton.test.tsx.snap
- client/src/components/DatasetsButton/index.ts
- client/src/components/SubPageNav/SubPageNav.module.scss
- client/src/components/SubPageNav/SubPageNav.module.scss.d.ts
- client/src/components/SubPageNav/SubPageNav.tsx
- client/src/components/SubPageNav/__snapshots__/SubPageNav.test.tsx.snap
- client/src/data/copy/explore.tsx
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- client/src/pages/methodology.tsx
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- client/src/styles/global.scss
QA - does the methodology page match Content 1.0?
> Update methodology page copy to Content 1.0

- data/data-pipeline/data_pipeline/etl/score/etl_score_post.py
> Add assertions around codebook

- data/data-pipeline/data_pipeline/etl/sources/tribal_overlap/etl.py
> Update tribal area names

- data/data-pipeline/data_pipeline/etl/sources/cdc_life_expectancy/etl.py
- data/data-pipeline/data_pipeline/etl/sources/cdc_places/etl.py
- data/data-pipeline/data_pipeline/etl/sources/cdc_svi_index/etl.py
- data/data-pipeline/data_pipeline/etl/sources/child_opportunity_index/etl.py
- data/data-pipeline/data_pipeline/etl/sources/dot_travel_composite/etl.py
- data/data-pipeline/data_pipeline/etl/sources/epa_rsei/etl.py
- data/data-pipeline/data_pipeline/etl/sources/hud_housing/etl.py
- data/data-pipeline/data_pipeline/etl/sources/hud_recap/etl.py
- data/data-pipeline/data_pipeline/etl/sources/mapping_inequality/etl.py
- data/data-pipeline/data_pipeline/etl/sources/national_risk_index/etl.py
- data/data-pipeline/data_pipeline/etl/sources/us_army_fuds/etl.py
- data/data-pipeline/poetry.lock
- data/data-pipeline/settings.toml
> Data source location

- data/data-pipeline/data_pipeline/etl/constants.py
- data/data-pipeline/data_pipeline/etl/sources/housing_and_transportation/etl.py
> Update file name pattern (#2037)

- .github/workflows/create-score-version.yml
Add a new action that allows us to manually create and upload score versions to s3.
> Add action for creating new score versions

- .github/workflows/create-score-version.yml
> Update namespaces for workflow

- client/src/components/DownloadButton/DownloadButton.module.scss
- client/src/components/DownloadButton/DownloadButton.module.scss.d.ts
- client/src/components/DownloadButton/DownloadButton.tsx
- client/src/components/PublicVideoBox/PublicVideoBox.module.scss
- client/src/components/PublicVideoBox/PublicVideoBox.module.scss.d.ts
- client/src/components/PublicVideoBox/PublicVideoBox.tsx
- client/src/components/PublicVideoBox/__snapshots__/PublicVideoBox.test.tsx.snap
- client/src/components/ReleaseUpdate/ReleaseUpdate.tsx
- client/src/data/copy/publicEngage.tsx
- client/src/intl/en.json
- client/src/pages/previous-versions.tsx
- client/src/pages/public-engagement.tsx
- client/src/pages/tests/__snapshots__/publicEng.test.tsx.snap
- Refactor download button to have gray buttons also
- Add a beta version of the PublicVideoBox in SCSS
- Update copy on Pub Eng page
> Update Pub Eng page

- client/src/data/copy/downloads.tsx
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
> Change geojson to shapefile

- .github/workflows/create-score-version.yml
- data/data-pipeline/data_pipeline/etl/constants.py
- data/data-pipeline/data_pipeline/etl/score/constants.py
- data/data-pipeline/data_pipeline/files/README-version-1.0.md
> Update score version workflow to also upload tiles

- data/data-pipeline/Dockerfile
- data/data-pipeline/data_pipeline/etl/constants.py
- docker-compose.yml
> Update the dockerfile

- client/src/data/copy/downloads.tsx
- client/src/intl/en.json
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
> Remove TSD link from download page

- client/src/components/TractDemographics/__snapshots__/TractDemographics.test.tsx.snap
- client/src/data/copy/explore.tsx
- client/src/intl/en.json
> fix typo on demographics

- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/components/DatasetCard/tests/__snapshots__/datasetCard.test.tsx.snap
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/Indicator/__snapshots__/Indicator.test.tsx.snap
- client/src/components/ReleaseUpdate/ReleaseUpdate.tsx
- client/src/components/ReleaseUpdate/__snapshots__/ReleaseUpdate.test.tsx.snap
- client/src/data/copy/explore.tsx
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- closes #2134
- closes #2135
- closes #2141
> fix: typos

- client/src/data/copy/about.tsx
- client/src/data/copy/faqs.tsx
- client/src/intl/en.json
- client/src/pages/about.tsx
- client/src/pages/frequently-asked-questions.tsx
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
> update memo and instruction links

- client/src/components/AreaDetail/AreaDetail.tsx
- client/src/components/DatasetCard/tests/__snapshots__/datasetCard.test.tsx.snap
- client/src/components/DatasetContainer/dsContainer.module.scss
- client/src/components/DatasetContainer/dsContainer.module.scss.d.ts
- client/src/components/DatasetContainer/index.tsx
- client/src/components/DatasetContainer/tests/__snapshots__/datasetContainer.test.tsx.snap
- client/src/components/DatasetsButton/DatasetsButton.module.scss
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- client/src/pages/about.tsx
- client/src/pages/contact.tsx
- client/src/pages/downloads.tsx
- client/src/pages/frequently-asked-questions.tsx
- client/src/pages/index.tsx
- client/src/pages/methodology.tsx
- client/src/pages/previous-versions.tsx
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
- client/src/pages/tests/__snapshots__/contact.test.tsx.snap
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- client/src/styles/global.scss
- closes #2159
- closes #2158
- closes #2157
- closes #2156
> Replace mail with launch icon, replace public eng btn with data source btn, copy update on Census, add census disclaimer text

- client/src/data/copy/about.tsx
- client/src/intl/en.json
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
> update EO date

- data/data-pipeline/data_pipeline/comparator.py
This is a small update to the comparator to include the number of disadvantaged tracts calculated in both scores, and the populations (as a % of the total population) of those disadvantaged tracts. It also includes a count of the census tracts newly marked as disadvantaged, as well as those that were marked as disadvantaged but have now changed.
> Add several factors to comparator, including number of disadvantaged tracts and population

- client/src/components/J40Header/J40Header.tsx
- client/src/components/J40Header/__snapshots__/J40Header.test.tsx.snap
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
- client/src/pages/tests/__snapshots__/contact.test.tsx.snap
- client/src/pages/tests/__snapshots__/downloads.test.tsx.snap
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- client/src/pages/tests/__snapshots__/publicEng.test.tsx.snap
- client/src/pages/tests/__snapshots__/techSupportDoc.test.tsx.snap
> remove release banner

- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/data/copy/faqs.tsx
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- closes #2205
- update snapshots
> update two typos

- client/src/data/copy/about.tsx
- client/src/intl/en.json
- client/src/pages/about.tsx
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
Add links to About page around tutorial
> add tutorial links

- client/src/components/Categories/__snapshots__/Categories.test.tsx.snap
- client/src/components/HowYouCanHelp/tests/__snapshots__/howYouCanHelp.test.tsx.snap
- client/src/data/copy/about.tsx
- client/src/data/copy/faqs.tsx
- client/src/data/copy/methodology.tsx
- client/src/intl/en.json
- client/src/pages/about.tsx
- client/src/pages/frequently-asked-questions.tsx
- client/src/pages/tests/__snapshots__/about.test.tsx.snap
- client/src/pages/tests/__snapshots__/freqAskedQuestions.test.tsx.snap
- client/src/pages/tests/__snapshots__/methodology.test.tsx.snap
- closes #2209
- closes #2210
- closes #2211
- closes #2213
- closes #2214
- closes #2215
> closes a number of tickets
